version: "3.2"
services:
  english_collateral_auction:
    build: .
    image: reflexer/auction-keeper
    env_file:
      - .env
    volumes:
      - $PWD/hush:/home/keeper/hush
      - $PWD/model:/home/keeper/model
    command: >
      bash -c "./auction-keeper --rpc-host=$${RPC_HOST} --rpc-port=$${RPC_PORT} \
      --eth-from=$${ETH_FROM} \
      --eth-key='key_file=/home/keeper/hush/auction.json,pass_file=/home/keeper/hush/auction.pass' \
      --collateral-auction-house=$${COLLATERAL_AUCTION_HOUSE_ADDRESS} \
      --liquidation-engine=$${LIQUIDATION_ENGINE_ADDRESS} \
      --model '/home/keeper/model/model.sh'"

  surplus_auction:
    image: reflexer/auction-keeper
    env_file:
      - .env
    volumes:
      - $PWD/hush:/home/keeper/hush
      - $PWD/model:/home/keeper/model
    command: >
      bash -c "./auction-keeper --rpc-host=$${RPC_HOST} --rpc-port=$${RPC_PORT} \
      --eth-from=$${ETH_FROM} \
      --eth-key='key_file=/home/keeper/hush/auction.json,pass_file=/home/keeper/hush/auction.pass' \
      --surpus-auction-house=$${SURPLUS_AUCTION_HOUSE_ADDRESS} \
      --accounting-engine=$${ACCOUNTING_ENGINE_ADDRESS} \
      --model '/home/keeper/model/model.sh'"

  debt_auction:
    image: reflexer/auction-keeper
    env_file:
      - .env
    volumes:
      - $PWD/hush:/home/keeper/hush
      - $PWD/model:/home/keeper/model
    command: >
      bash -c "./auction-keeper --rpc-host=$${RPC_HOST} --rpc-port=$${RPC_PORT} \
      --eth-from=$${ETH_FROM} \
      --eth-key='key_file=/home/keeper/hush/auction.json,pass_file=/home/keeper/hush/auction.pass' \
      --debt-auction-house=$${DEBT_AUCTION_HOUSE_ADDRESS} \
      --accounting-engine=$${ACCOUNTING_ENGINE_ADDRESS} \
      --model '/home/keeper/model/model.sh'"
